### ISSUE TITLE
Cannot read properties of undefined (reading 'text')

### ISSUE THREAD

**Issue by lawetis** [anthropics/anthropic-sdk-typescript#244]
When using the `beta.messages.stream` function, the following error will occur if the input is not in English.

I used try catch to catch the following error:

```bash
AnthropicError: Cannot read properties of undefined (reading 'text')
    at /node_modules/@anthropic-ai/sdk/src/lib/MessageStream.ts:298:46
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: TypeError: Cannot read properties of undefined (reading 'text')
      at MessageStream._MessageStream_addStreamEvent (/node_modules/@anthropic-ai/sdk/src/lib/MessageStream.ts:373:79)
      at MessageStream._createMessage (/node_modules/@anthropic-ai/sdk/src/lib/MessageStream.ts:140:27)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
}
Error: Cannot read properties of undefined (reading 'text')
    at /node_modules/@anthropic-ai/sdk/src/lib/MessageStream.ts:298:46
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

```

**Comment by rattrayalex** [comment]
Thanks for reporting; can you share code / prompt to reproduce this?

cc @yjp20

**Comment by lawetis** [comment]
```
import Anthropic from '@anthropic-ai/sdk';

const anthropic = new Anthropic();

async function main() {
  const stream = anthropic.beta.messages
    .stream({
      model: 'claude-2.1',
      max_tokens: 1024,
      messages: [
        {
          role: 'user',
          content: 'こんにちは、あなたのお名前は',
        },
      ],
    })
    .on('text', (text) => {
      console.log(text);
    });

  const message = await stream.finalMessage();
  console.log(message);
}

main();
```

As shown in the above code, this error will occur if the user role input is not in English.

**Comment by rattrayalex** [comment]
Thanks. We've found this to be a problem in the underlying API, not the SDK, and hope to have a fix in the coming days.

**Comment by lawetis** [comment]
Thanks, looking forward to fixing this issue.

**Comment by rattrayalex** [comment]
Fix went live a week ago!
