### ISSUE TITLE
Not returning error while streaming

### ISSUE THREAD

**Issue by XpTo2k** [anthropics/anthropic-sdk-typescript#298]
API Version: 0.14.1

I'm trying to handle some errors (ie: api key error) while using the stream api.

I've noticed that when api casts an error on stream api, it returns empty stream and it cast the error on a node module level.
I will give you an example bellow:

```typescript
completion = this.service.messages.stream({
  max_tokens: this.maxTokens,
  model: this.model,
  messages,
});
```

If the code above errors (ie: wrong api key) it will returns:
```typescript
MessageStream {
  messages: [ { role: 'user', content: 'recipe for creme brulee' } ],
  receivedMessages: [],
  controller: AbortController { signal: AbortSignal { aborted: false } }
}
```

And it throws this terminal error and breaks my api:
```
C:\Users\xpto\Documents\GitHub\UNF_002-LLM-HUB\engine\node_modules\@anthropic-ai\sdk\src\error.ts:62
      return new AuthenticationError(status, error, message, headers);
             ^
Error: 401 {"type":"error","error":{"type":"authentication_error","message":"invalid x-api-key"}}
    at Function.generate (C:\Users\xpto\Documents\GitHub\UNF_002-LLM-HUB\engine\node_modules\@anthropic-ai\sdk\src\error.ts:62:14)
    at Anthropic.makeStatusError (C:\Users\xpto\Documents\GitHub\UNF_002-LLM-HUB\engine\node_modules\@anthropic-ai\sdk\src\core.ts:383:21)
    at Anthropic.makeRequest (C:\Users\xpto\Documents\GitHub\UNF_002-LLM-HUB\engine\node_modules\@anthropic-ai\sdk\src\core.ts:446:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at MessageStream._createMessage (C:\Users\xpto\Documents\GitHub\UNF_002-LLM-HUB\engine\node_modules\@anthropic-ai\sdk\src\lib\MessageStream.ts:134:20)
``` 

Without using stream api this error is returned without problem.
Hope you guys can help!

**Comment by RobertCraigie** [comment]
> Without using stream api this error is returned without problem.

What do you mean? Other methods will also raise an error on an invalid API key

**Comment by XpTo2k** [comment]
> > Without using stream api this error is returned without problem.
> 
> What do you mean? Other methods will also raise an error on an invalid API key

the issue is not the error but the way its being returned or not. 

Example where the error is being return without a problem:
```typescript
result = await this.service.messages.create(request);
```
If this has, for example an api key error, it will return the error an I can handle it on my end.

The problem is with stream api as mentioned above, the same example will throw an error on node modules (breaking the api) and returns a MessageStream that is empty.

**Comment by RobertCraigie** [comment]
> If this has, for example an api key error, it will return the error an I can handle it on my end.

Do you mean an error is thrown? We do not return errors anywhere.

> The problem is with stream api as mentioned above, the same example will throw an error on node modules (breaking the api) and returns a MessageStream that is empty.

I'm confused, can you share a complete script?

With this script:
```ts
  const stream = client.messages.stream({
    messages: [
      {
        role: 'user',
        content: `Hey Claude! How can I recursively list all files in a directory in Rust?`,
      },
    ],
    model: 'claude-2.1',
    max_tokens: 1024,
  });

  for await (const event of stream) {
    console.log('event', event);
  }
```

If I have an invalid API key, an error is thrown. Is it not for you?

**Comment by XpTo2k** [comment]
This is the script:
```typescript
private async streamMessages(messages: Anthropic.Messages.MessageParam[]) {
    try {
      const completion = this.service.messages.stream({
        max_tokens: this.maxTokens,
        model: this.model,
        messages,
      });

      for await (const chunk of completion) {
        if (chunk.type === 'content_block_delta') {
          this.events.addEvent({
            data: chunk.delta.text,
            type: EventMessageType.message,
          });
        }
      }
      console.log('streamMessages', completion);
    } catch (e) {
      console.log('streamMessages error', e);
      this.responseErrorToCommonErrors(e?.status, e?.error);
    }
  }
  ```
  If the api key is wrong this try catch will not error out as the `this.service.messages.stream` will return a empty MessageStream. But an error is thrown at the module level:
  
  ```
  C:\Users\xpto\Documents\GitHub\UNF_002-LLM-HUB\engine\node_modules\@anthropic-ai\sdk\src\error.ts:62
      return new AuthenticationError(status, error, message, headers);
             ^
Error: 401 {"type":"error","error":{"type":"authentication_error","message":"invalid x-api-key"}}
    at Function.generate (C:\Users\xpto\Documents\GitHub\UNF_002-LLM-HUB\engine\node_modules\@anthropic-ai\sdk\src\error.ts:62:14)
    at Anthropic.makeStatusError (C:\Users\xpto\Documents\GitHub\UNF_002-LLM-HUB\engine\node_modules\@anthropic-ai\sdk\src\core.ts:383:21)
    at Anthropic.makeRequest (C:\Users\xpto\Documents\GitHub\UNF_002-LLM-HUB\engine\node_modules\@anthropic-ai\sdk\src\core.ts:446:24)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at MessageStream._createMessage (C:\Users\xpto\Documents\GitHub\UNF_002-LLM-HUB\engine\node_modules\@anthropic-ai\sdk\src\lib\MessageStream.ts:134:20)
    ```

**Comment by RobertCraigie** [comment]
Unfortunately I cannot reproduce this, here's my script

```ts
#!/usr/bin/env -S npm run tsn -T

import Anthropic from '@anthropic-ai/sdk';

const client = new Anthropic({ apiKey: 'foo' });

async function main() {
  try {
    const stream = client.messages.stream({
      messages: [
        {
          role: 'user',
          content: `Hey Claude! How can I recursively list all files in a directory in Rust?`,
        },
      ],
      model: 'claude-2.1',
      max_tokens: 1024,
    });

    for await (const event of stream) {
      console.log('event', event);
    }

    const message = await stream.finalMessage();
    console.log('finalMessage', message);
  } catch (e) {
    console.log('got error', e);
  }
}

main();
```

Running this successfully logs `got error AuthenticationError: 401 ...`

**Comment by XpTo2k** [comment]
```typescript
const message = await stream.finalMessage();
console.log('finalMessage', message);
```

can you check if it still works if you remove these 2 lines of code?

I did add `const message = await stream.finalMessage();` even without using it and now it works.
Kinda strange.

**Comment by RobertCraigie** [comment]
Ahhh I can reproduce your issue after removing that line, thanks! We'll look into this.

**Comment by rattrayalex** [comment]
This should be fixed now! Please comment if you can still reproduce the problem on the latest version.

**Comment by XpTo2k** [comment]
Hi again, 
Its way better now but there is still this wierd case that we always need to do a for await for the auth error to be thrown.
Check the empty loop bellow:

```typescript
private async streamMessages(messages: Anthropic.Messages.MessageParam[]) {
    let completion: MessageStream;
    try {
      completion = this.service.messages.stream({
        max_tokens: this.maxTokens,
        model: this.model,
        messages,
      });
      //! This is needed as the api still has this wierd behaviour that only throws the error when we try to read the chunk
      for await (const chunk of completion) {
      }
    } catch (e) {
      console.log('AUTH ERROR OR OTHER (BEFORE ANY STREAM)');
      this.responseErrorToCommonErrors(e?.status, e?.error);
    }

    try {
      for await (const chunk of completion) {
        if (chunk.type === 'content_block_delta') {
          this.events.addEvent({
            data: chunk.delta.text,
            type: EventMessageType.message,
          });
        }
      }
    } catch (e) {
      console.log('STREAM ERRORS');
      this.events.error(e);
    }
  }
  ```
