### ISSUE TITLE
Prompt caching

### ISSUE THREAD

**Issue by Kaankoska22** [anthropics/anthropic-sdk-typescript#628]
Hi I couldn't make this call work what am I doing wrong?

const response = await anthropic.beta.prompt_caching.messages.create({
        betas: ['prompt-caching-2024-07-31'],
        model: "claude-3-5-sonnet-20241022",
        max_tokens: 1024,
        system: [
            {
                type: "text",
                text: "You are an AI assistant tasked with analyzing literary works. Your goal is to provide insightful commentary on themes, characters, and writing style.\n",
            },
            {
                type: "text",
                text: Bigprompt,
                cache_control: { type: "ephemeral" }
            }
        ],
        messages: [
            {
                role: "user",
                content: "example query"
            }
        ]
    });

**Comment by IbrohimIsroilov** [comment]
I think they disabled promptCaching, countTokens. 

function makeBetaResource(client: AnthropicBedrock): BetaResource {
  const resource = new Resources.Beta(client);

  // @ts-expect-error we're deleting non-optional properties
  delete resource.promptCaching;

  // @ts-expect-error we're deleting non-optional properties
  delete resource.messages.batches;

  // @ts-expect-error we're deleting non-optional properties
  delete resource.messages.countTokens;

  return resource;
}

**Comment by goodroot** [comment]
I don't think this is in the SDK yet :)

**Comment by Zundrium** [comment]
Any idea when this will be added?

**Comment by alist** [comment]
GCP Documentation, last updated Jan 17 2025 specifies Vertex AI supports Prompt Caching for Sonnet 3.5 V2 - requesting an undeletion of those properties please :-) 

https://cloud.google.com/vertex-ai/generative-ai/docs/partner-models/claude-prompt-caching

**Comment by RobertCraigie** [comment]
Hey all, prompt caching is in GA now and is accessible through the standard `client.messages.create()` method. The deletion of `.beta.promptCaching` was accidentally left-over from before it was GA and wasn't actually doing anything on the latest version!

**Comment by alist** [comment]
Thanks @RobertCraigie - I will say I am getting a runtime error here:


```
TypeError: Resources.Beta is not a constructor
    at makeBetaResource (/app/node_modules/@anthropic-ai/vertex-sdk/src/client.ts:189:20)
    at AnthropicVertex (/app/node_modules/@anthropic-ai/vertex-sdk/src/client.ts:87:24)
    at AnthropicVertexApiClient.initialize (/app/worker/src/lib/llm/anthropic/llm_anthropic_vertex_adapter.ts:18:19)
    at AnthropicLlmApiClient.initialize (/app/worker/src/lib/llm/anthropic/llm_anthropic_api_client.ts:54:28)
```


`vertex-sdk` in yarn.lock:

```yaml
"@anthropic-ai/vertex-sdk@^0.6.1":
  version "0.6.1"
  resolved "https://registry.yarnpkg.com/@anthropic-ai/vertex-sdk/-/vertex-sdk-0.6.1.tgz#1aeb29755264c090c4aa873dd546d1868dd0f501"
  integrity sha512-Ckw0Dv/LDSt/ct3v19Jwd8gSQEv7ReDreXHrZTuJ+VWytTZW7W7465UG+it6InsT64wHUgsxnh0EYKXw89Tp7Q==
  dependencies:
    "@anthropic-ai/sdk" ">=0.14 <1"
    google-auth-library "^9.4.2"
```

Utilizing: 

```yaml
"@anthropic-ai/sdk@>=0.14 <1":
  version "0.24.0"
  resolved "https://registry.npmjs.org/@anthropic-ai/sdk/-/sdk-0.24.0.tgz"
  integrity sha512-iMb1bQimQrSw/Rq6duPiuCJ7uvlSciq5PWp17jVOfy5dK2EJY36ol10ttwb+Zf6yzkKHMdt+vNIpznj/HsPXOg==
  dependencies:
    "@types/node" "^18.11.18"
    "@types/node-fetch" "^2.6.4"
    abort-controller "^3.0.0"
    agentkeepalive "^4.2.1"
    form-data-encoder "1.7.2"
    formdata-node "^4.3.2"
    node-fetch "^2.6.7"
    web-streams-polyfill "^3.2.1"
```

My usage 

```ts
    this.client = new AnthropicVertex({
      projectId: await GetSecret('GCP_PROJECT_ID'),
      region: 'us-east5',
    });
```

Maybe the `@anthropic-ai/sdk` version needs to be locked down a bit more?

**Comment by RobertCraigie** [comment]
> Maybe the @anthropic-ai/sdk version needs to be locked down a bit more?

ah probably, does it work when you bump `@anthropic-ai/sdk` to the latest version?

**Comment by alist** [comment]
That did the trick! Checked it- v0.33 and v0.35 both work....

I see you're using this dependency on the package.json on vertex-sdk (ts sdk main branch):

```json
    "@anthropic-ai/sdk": "file:../../dist/",
```

However this shows up in package.json when I do a fresh `yarn add @anthropic-ai/vertex-sdk` (ie `0.6.1`):

```json
    "@anthropic-ai/sdk": ">=0.14 <1",
````

So I must confess I'm not sure what's going on here with the population of the `>=14 <1`.

In any case, the fresh install takes a newer release of `sdk` `0.35.0`. Removing the `>=14 <1` section from my old yarn file and doing a new yarn install does the trick.

Would recommend updating the min version (wherever it is you do that ;)).

**Comment by RobertCraigie** [comment]
Awesome thanks, will bump the dependency range!

For the curious it is set in a build script [here](https://github.com/anthropics/anthropic-sdk-typescript/blob/0c466396618b574be0336402c62f5b6df817f6ed/packages/vertex-sdk/scripts/postprocess-dist-package-json.cjs#L7).
