### ISSUE TITLE
New builtin fetch alpha

### ISSUE THREAD

**Issue by RobertCraigie** [anthropics/anthropic-sdk-typescript#645]
We've been working on an alpha version of the SDK that alongside many other cleanups, migrates from `node-fetch` to builtin fetch.

You can try it out by installing the `0.34.0-alpha.0` version:

```sh
pnpm add @anthropic-ai/sdk@alpha
```

The core happy path of the SDK remains the same, your existing method calls should just work! However you may run into typing issues as we now expect that `fetch` is defined as a global.

There are many other small breaking changes which you may run into, we'll share a full migration guide as soon as possible.

---

Please share feedback on anything you think could be improved or if you run into any issues! Hope this is a nice early present for you all :)

> [!IMPORTANT]  
> Unfortunately we cannot guarantee support over the holiday break (December 20th - January 6th inclusive) but we will go through every comment as soon as possible.

**Comment by Nishchit14** [comment]
[ky](https://github.com/sindresorhus/ky) is a great replacement of fetch (it's a wrapper with great DX., sharing here incase you'd like to consider it.

**Comment by RobertCraigie** [comment]
Thanks! However we're not considering other HTTP libraries as one great benefit of just depending on the builtin `fetch` function is that, among other things, we now have zero dependencies!

**Comment by Nishchit14** [comment]
Agree, But ky has zero deps and works best for browser, Node, Bun etc. Just a suggestion.

![Image](https://github.com/user-attachments/assets/a24e48cb-105e-43f5-898d-8309134221e2)

**Comment by pelikhan** [comment]
do you have a migration guide to support httpAgent from https://www.npmjs.com/package/https-proxy-agent ?

**Comment by RobertCraigie** [comment]
@pelikhan we haven't tested `https-proxy-agent` directly yet but here's what setting a proxy would look like in a couple different runtimes

Node:
```ts
import Anthropic from '@anthropic-ai/sdk';
import * as undici from 'undici';

const dispatcher = new undici.ProxyAgent('http://localhost:8888');

const client = new Anthropic({
  fetch(url, init = {}) {
    return undici.fetch(url, {
      ...(init as unknown as undici.RequestInit),
      dispatcher,
    }) as unknown as Promise<Response>;
  },
});
```

Bun:
```ts
import Anthropic from '@anthropic-ai/sdk';

const client = new Anthropic({
  fetch(url, init) {
    return fetch(url, { ...init, proxy: 'http://localhost:8888' });
  },
});
```

Deno:
```ts
import Anthropic from '@anthropic-ai/sdk';

const httpClient = Deno.createHttpClient({ proxy: { url: 'http://localhost:8888' } });

const client = new Anthropic({
  fetch(url, init) {
    return fetch(url, { ...init, client: httpClient });
  },
});
```

**Comment by pelikhan** [comment]
node-openai used this library already

**Comment by RobertCraigie** [comment]
@pelikhan sorry what do you mean?

**Comment by pelikhan** [comment]
Here are the docs about using a proxy with node-openai --> https://github.com/openai/openai-node?tab=readme-ov-file#configuring-an-https-agent-eg-for-proxies

**Comment by RobertCraigie** [comment]
Ah, I think passing the `httpAgent` client option isn't working right now but the examples I shared should work for now.

**Comment by arvinxx** [comment]
hi @RobertCraigie , I'm wondering is the alpha vesion be stable now? We are meeting an issue of 

```
Error: you must `import '@anthropic-ai/sdk/shims/web'` before importing anything else from @anthropic-ai/sdk

    at c (.next/server/chunks/2859.js:1:53930)

    at 588127 (.next/server/chunks/2859.js:2:5650)

    at t (.next/server/webpack-runtime.js:1:143)

    at 151336 (.next/server/chunks/21167.js:528:6818)
```

but actually we have imported the shims before:

```ts
// sort-imports-ignore
import '@anthropic-ai/sdk/shims/web';
import Anthropic from '@anthropic-ai/sdk';

// ...
```

and we are using `^0.33` now. I'm not sure whether the new alpha verion will still need the shims import

**Comment by RobertCraigie** [comment]
@arvinxx thanks for the report, yeah the alpha version should be stable.

The shims aren't needed at all in the new version so I'm surprised you're seeing that error, maybe you have multiple versions of the SDK installed somehow?

**Comment by transitive-bullshit** [comment]
Just wanted to say that this looks perfect 💪 

Also love that you can optionally override the default, global `fetch`.

For Node.js, this should also work using undici's new [EnvHttpProxyAgent](https://github.com/nodejs/undici/blob/main/docs/docs/api/EnvHttpProxyAgent.md).

```ts
import Anthropic from '@anthropic-ai/sdk';
import { EnvHttpProxyAgent } from 'undici';

const dispatcher = new EnvHttpProxyAgent();

const client = new Anthropic({
  fetch(url, init = {}) {
    return fetch(url, { dispatcher, ...init });
  },
});
```

**Comment by RobertCraigie** [comment]
Update: we'll be shipping these changes as a stable in the coming days :)

**Comment by whistle003** [comment]
Error: you must `import '@anthropic-ai/sdk/shims/web'` before importing anything else from @anthropic-ai/sdk
我也遇到了同样的问题，最新版本

**Comment by shigomany** [comment]
I have same problem now.

```log
⨯ Error: you must `import '@anthropic-ai/sdk/shims/web'` before importing anything else from @anthropic-ai/sdk

    at u (.next/server/chunks/18932.js:103:150597)

    at 833206 (.next/server/chunks/18932.js:204:35106)

    at t (.next/server/webpack-runtime.js:1:143)

    at 196865 (.next/server/chunks/917.js:124:9721)

    at t (.next/server/webpack-runtime.js:1:143)

    at <unknown> (.next/server/chunks/917.js:1067:309)

    at t.a (.next/server/webpack-runtime.js:1:989)

    at 815998 (.next/server/chunks/917.js:1067:125)

    at t (.next/server/webpack-runtime.js:1:143)

    at <unknown> (.next/server/chunks/917.js:1:11848) {

  digest: '3455927945'

}
```

**Comment by RobertCraigie** [comment]
@whistle003 @shigomany are you sure you're using the alpha version and you don't have two versions installed at once? That error shouldn't exist in the new version.

**Comment by shigomany** [comment]
I used [lobe-chat](https://github.com/lobehub/lobe-chat) from @arvinxx, which self built Docker container.

These used version in `package.json`: "@anthropic-ai/sdk": "^0.39.0"

**Comment by arvinxx** [comment]
@RobertCraigie when will the new fetch release in stable? We want to remove the shims.

**Comment by RobertCraigie** [comment]
This was just released in `v0.50.1`!

Please try it out and let us know if you run into any issues. I strongly recommend reading the migration [guide](https://github.com/anthropics/anthropic-sdk-typescript/blob/main/MIGRATION.md).
